Controllers/DashboardsController.cs
using Hotel_Management_MVC.Models;
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System.Data;
using System.Net.Mail;
using System.Net;
using Microsoft.AspNetCore.Authorization;
using System.Dynamic;

namespace Hotel_Management_MVC.Controllers
{
    public class DashboardsController : Controller
    {
        private readonly AdvancedTestDbContext _dbContext;
        public DashboardsController(AdvancedTestDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult UsersDashboard()
        {
            if (!String.IsNullOrEmpty(HttpContext.Session.GetString("UserEmail")))
            {
                List<SqlParameter> parameters = new List<SqlParameter>();
                Base _base = new Base();

                DataTable dt = _base.GetDataTable("sp_displayHotels", parameters, CommandType.StoredProcedure);

                List<HotelsAvailable> hotelList = new List<HotelsAvailable>();

                if (dt != null && dt.Rows.Count > 0)
                {
                    foreach (DataRow row in dt.Rows)
                    {
                        HotelsAvailable hotel = new HotelsAvailable();

                        hotel.HotelId = Convert.ToInt32(row["HotelId"]);
                        hotel.HotelName = row["HotelName"].ToString();
                        hotel.DoubleBedAc = Convert.ToInt32(row["DoubleBedAc"]);
                        hotel.SingleBedAc = Convert.ToInt32(row["SingleBedAc"]);
                        hotel.DoubleBedNonAc = Convert.ToInt32(row["DoubleBedNonAc"]);
                        hotel.SingleBedNonAc = Convert.ToInt32(row["SingleBedNonAc"]);
                        hotel.MaharajaSuite = Convert.ToInt32(row["MaharajaSuite"]);
                        hotel.CoverImgUrl = row["CoverImgUrl"].ToString();
                        hotel.SingleBedAcImgUrl = row["SingleBedAcImgUrl"].ToString();
                        hotel.DoubleBedAcImgUrl = row["DoubleBedAcImgUrl"].ToString();
                        hotel.SingleBedNonAcImgUrl = row["SingleBedNonAcImgUrl"].ToString();
                        hotel.DoubleBedNonAcImgUrl = row["DoubleBedNonAcImgUrl"].ToString();
                        hotel.SingleBedAcPrice = (double)row["SingleBedAcPrice"];
                        hotel.DoubleBedAcPrice = (double)row["DoubleBedAcPrice"];
                        hotel.SingleBedNonAcPrice = (double)row["SingleBedNonAcPrice"];
                        hotel.DoubleBedNonAcPrice = (double)row["DoubleBedNonAcPrice"];


                        hotelList.Add(hotel);
                    }
                }
                return View(hotelList);

            }

            else
            {
                return RedirectToAction("UserLogin", "Accounts");
            }
        }

        public IActionResult HotelDashboard(string hotelName)
        {
            if (!String.IsNullOrEmpty(HttpContext.Session.GetString("HotelEmail")))
            {
                List<HotelBookings> bookingDetails = _dbContext.HotelBookings.Where(
                e => e.HotelName == hotelName).ToList();
                return View(bookingDetails);
            }

            else
            {
                return RedirectToAction("HotelLogin", "Accounts");
            }

        }

        public IActionResult AdminDashboard()
        {
            if (!String.IsNullOrEmpty(HttpContext.Session.GetString("AdminEmail")))
            {
                List<HotelDetail> hotelDetails = _dbContext.HotelDetails.ToList();
                List<UserDetails> userDetails = _dbContext.UserDetails.ToList();

                dynamic adminDashboardDetails = new ExpandoObject();

                adminDashboardDetails.HotelDetail = hotelDetails;
                adminDashboardDetails.UserDetails = userDetails;

                return View(adminDashboardDetails);
            }   

            else
            {
                return RedirectToAction("AdminLogin", "Accounts");
            }
        }

        public IActionResult GrantHotelAccess(string id)
        {

            List<SqlParameter> parameters = new List<SqlParameter>();
            parameters.Add(new SqlParameter("@id", id));
            Base _base = new Base(); 

            _base.GetDataTable("sp_updateHtelDetails", parameters, CommandType.StoredProcedure);
            SendAcceptanceEmail(id);
            return RedirectToAction("AdminDashboard");

        }

        public void SendAcceptanceEmail(string id)
        {
            var hotel = _dbContext.HotelDetails.SingleOrDefault(e => e.Id == id);
            if(hotel != null)
            {
                try
                {
                    string emailId = hotel.Email;
                    var verifyUrl = "/Accounts/HotelLogin";
                    string url = Request.GetDisplayUrl();
                    var link = url.Replace("/Dashboards/GrantHotelAccess/" + id, verifyUrl);

                    var fromEmail = new MailAddress("tolanihitesh1018@gmail.com", "Hotel Management");
                    var toEmail = new MailAddress(emailId);
                    var fromEmailPassword = "lzubezgjkphblnfm";
                    string subject = "Application Accepted!";

                    string body = "<br/><h3>Greetings!<h3><br/>" +
                        "Welcome to Infinite Hotels<br/>" +
                        "<br/>We would like to inform you that your Application has been accepted<br/>" +
                        "<br/>and your Hotel is successfully Registered!<br/>" +
                        "<br/>Please follow the link below to Login to your Account!<br/>" +
                        "<br/> <a href = '" + link + "'> Login </a>";

                    var smtpRequest = new SmtpClient
                    {
                        Host = "smtp.gmail.com",
                        Port = 587,
                        EnableSsl = true,
                        DeliveryMethod = SmtpDeliveryMethod.Network,
                        UseDefaultCredentials = false,
                        Credentials = new NetworkCredential(fromEmail.Address, fromEmailPassword)
                    };

                    using (var message = new MailMessage(fromEmail, toEmail)
                    {
                        Subject = subject,
                        Body = body,
                        IsBodyHtml = true
                    }) smtpRequest.Send(message);

                }

                catch (Exception ex)
                {
                    throw ex;
                };
            }
            
        }

        public async Task<IActionResult> SelectRooms(int id)
        {
            List<SqlParameter> parameters = new List<SqlParameter>();
            parameters.Add(new SqlParameter("@id", id));
            Base _base = new Base();

            DataTable dt = _base.GetDataTable("sp_displayHotels", parameters, CommandType.StoredProcedure);

            List<HotelsAvailable> hotelList = new List<HotelsAvailable>();
            if (dt != null && dt.Rows.Count > 0)
            {
                foreach (DataRow row in dt.Rows)
                {
                    HotelsAvailable hotel = new HotelsAvailable();

                    hotel.HotelId = Convert.ToInt32(row["HotelId"]);
                    hotel.HotelName = row["HotelName"].ToString();
                    hotel.DoubleBedAc = Convert.ToInt32(row["DoubleBedAc"]);
                    hotel.SingleBedAc = Convert.ToInt32(row["SingleBedAc"]);
                    hotel.DoubleBedNonAc = Convert.ToInt32(row["DoubleBedNonAc"]);
                    hotel.SingleBedNonAc = Convert.ToInt32(row["SingleBedNonAc"]);
                    hotel.MaharajaSuite = Convert.ToInt32(row["MaharajaSuite"]);
                    hotel.CoverImgUrl = row["CoverImgUrl"].ToString();
                    hotel.SingleBedAcImgUrl = row["SingleBedAcImgUrl"].ToString();
                    hotel.DoubleBedAcImgUrl = row["DoubleBedAcImgUrl"].ToString();
                    hotel.SingleBedNonAcImgUrl = row["SingleBedNonAcImgUrl"].ToString();
                    hotel.DoubleBedNonAcImgUrl = row["DoubleBedNonAcImgUrl"].ToString();
                    hotel.SingleBedAcPrice = (double)row["SingleBedAcPrice"];
                    hotel.DoubleBedAcPrice = (double)row["DoubleBedAcPrice"];
                    hotel.SingleBedNonAcPrice = (double)row["SingleBedNonAcPrice"];
                    hotel.DoubleBedNonAcPrice = (double)row["DoubleBedNonAcPrice"];

                    hotelList.Add(hotel);
                }
            }
            return View(hotelList);
        }

        public async Task<IActionResult> BookRoom(string roomType, int id)
        {
            List<SqlParameter> parameters = new List<SqlParameter>();
            parameters.Add(new SqlParameter("@id", id));
            Base _base = new Base();

            DataTable dt = _base.GetDataTable("sp_displayHotels", parameters, CommandType.StoredProcedure);

            BookingDetails bookingDetails = new BookingDetails();
            if (dt != null && dt.Rows.Count > 0)
            {
                foreach (DataRow row in dt.Rows)
                {
                    bookingDetails.HotelId = Convert.ToInt32(row["HotelId"]);
                    bookingDetails.HotelName = row["HotelName"].ToString();
                    bookingDetails.HotelCoverImg = row["CoverImgUrl"].ToString();
                    bookingDetails.UserEmail = HttpContext.Session.GetString("UserEmail");
                    bookingDetails.NoOfRooms = 1;

                    if (roomType == "DoubleBedAc")
                    {
                        bookingDetails.RoomTypeNo = Convert.ToInt32(row["DoubleBedAc"]);
                        bookingDetails.NoOfGuests = 2;
                        bookingDetails.RoomTypeString = "Double Bed Ac";

Views/Dashboards/AdminDashboard.cshtml
@model dynamic

    <div class="text-center p-2">
        <h3>Admin Dashboard</h3>
    </div>
    </br>

<h4>Hotel Requests</h4>
<hr/>
<table class="table" id="HotelReq">
  <thead>
    <tr>
      <th>Hotel Name</th>
      <th>Email</th>
      <th>Single-Bed AC Rooms</th>
      <th>Double-Bed AC Rooms</th>
      <th>Single-Bed Non-AC Rooms</th>
      <th>Double-Bed Non-AC Rooms</th>
      <th>Suits</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
        @foreach (var item in Model.HotelDetail)
        {
            <tr>
                <td>@item.HotelName</td>
                <td>@item.Email</td>
                <td>@item.SingleBedAc</td>
                <td>@item.DoubleBedAc</td>
                <td>@item.SingleBedNonAc</td>
                <td>@item.DoubleBedNonAc</td>
                <td>@item.MaharajaSuite</td>
                @if (item.EmailVerified == true)
                {
                    <td>
                        <button type="button" class="btn btn-warning"
                        data-bs-toggle="modal" data-bs-target="#deleteModal" asp-route-id="@item.Id">
                            Edit
                        </button>
                    </td>

                    <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">@item.HotelName</h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                    Select What you want to do
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-warning">Edit</button>
                                    <button type="button" class="btn btn-danger" asp-controller="Dashboards" asp-action="DeleteHotel" asp-route-id="@item.Id">Delete</button>
                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                </div>
                            </div>
                        </div>
                    </div>
                }
                else
                {
                    <td>
                        <a type="button" class="btn btn-success" asp-controller="Dashboards" asp-action="GrantHotelAccess" asp-route-id="@item.Id">Accept</a>
                    </td>
                }
                
            </tr>
        }
  </tbody>
</table>

</br>
</br>
</br>

<h4>User Details</h4>
<hr />
<table class="table" id="usersTab">
    <thead>
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th>Joining Date & Time</th>
            <th>Details</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.UserDetails)
        {
            <tr>
                <td>@item.FirstName</td>
                <td>@item.LastName</td>
                <td>@item.Email</td>
                <td>@item.CreationDate</td>
                <td>
                    <button type="button" class="btn btn-success">Details</button>
                </td>

            </tr>
        }
    </tbody>
</table>

@*<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.js"></script> *@

<script type="text/javascript">

    $(document).ready(function () {
        $('#HotelReq').DataTable();
        $('#usersTab').DataTable();
    });
</script>

Views/Dashboards/BookingSummary.cshtml
@model BookingDetails

<div class="container MainContainer">
    <div class="row MainRow justify-content-center pt-5">
        <div class="col-lg-6 col-md-8 mx-auto MainCol shadow-lg p-3 mb-5 rounded text-center">
            <h4>Booking Summary</h4>
            <hr />

            <span>
                Name : @Model.Name
            </span>
            <br />

            <span>
                Hotel Name : @Model.HotelName
            </span>
            <br />

            <span>
                No. Of Guests : @Model.NoOfGuests
            </span>
            <br />

            <span>
                Check In Date : @Model.CheckInDate
            </span>
            <br />

            <span>
                Check Out Date : @Model.CheckOutDate
            </span>
            <br />

            <span>
                Room Type : @Model.RoomTypeString
            </span>
            <br />

            <span>
                No. Of Rooms : @Model.NoOfRooms
            </span>
            <br />

            <span>
                Room Price : @Model.RoomPrice
            </span>
            <br />

            <span>
                Per Night Charge (Room Price x No. Of Rooms) : @Model.AmountPerNight
            </span>
            <br />

            <span>
                Total Bill (Per Night Charge x No. Of Days Stay) : @Model.TotalAmount
            </span>
            <br />

            <span>
                Id Proof : @Model.IdProofType
            </span>
            <br />

            <div class="pt-4">
                <a href="@Url.Action("UserBookingsTab", "Dashboards", new { email = Model.UserEmail})" class="btn btn-primary">Dashboard</a>
            </div>
        </div>
    </div>
</div>

Views/Dashboards/HotelDashboard.cshtml
@model List<HotelBookings>
@inject IHttpContextAccessor context


<div class="text-center pb-5">
    <h3>Hotel Dashboard</h3>
</div>

<table class="table" id="HotelDb">
    <thead>
        <tr>
            <th>#No.</th>
            <th>Guest Name</th>
            <th>No. of Rooms</th>
            <th>No. of Guests</th>
            <th>Room Type</th>
            <th>Id Proof Type</th>
            <th>Id Proof No.</th>    
            <th>Details</th>    
        </tr>
    </thead>
    <tbody>
        @{
            int i = 1;
        }
        @foreach (var item in Model)
        {
            <tr>
                <td>@i</td>
                <td>@item.GuestName</td>
                <td>@item.NoOfRooms</td>
                <td>@item.NoOfGuests</td>
                <td>@item.RoomType</td>
                <td>@item.IdProofType</td>
                <td>@item.IdProofNumber</td>
                <td>
                    <button type="button" class="btn btn-success">View</button>
                </td>
                
            </tr>
        }
    </tbody>
</table>

<script type="text/javascript">
    $(document).ready(function () {
        $('#HotelDb').DataTable();
    });
</script>

Views/Dashboards/SelectRooms.cshtml
@model List<HotelsAvailable>

@{
    ViewData["Title"] = "User Dashboard";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-6"">
        @foreach(var hotel in Model)
        {
            <div class="text-center align-items-center justify-content-center">
                <img src="@hotel.CoverImgUrl" width="400" height="200" />
                <h2>Hotel @hotel.HotelName</h2>
            </div>
            
        }
        </div>

        <br/>

        <div>
            @Html.Partial("_ChooseRoomType", Model)
        </div>
    </div>
</div>

Views/Dashboards/UserBookingsTab.cshtml
@model List<BookingDetails>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Hotel Name</th>
      <th scope="col">No. Of Guests</th>
      <th scope="col">Check In Date</th>
      <th scope="col">Check Out Date</th>
      <th scope="col">Room Type</th>
      <th scope="col">No. Of Rooms</th>
      <th scope="col">Room Price</th>
      <th scope="col">Per Night Charge</th>
      <th scope="col">Total Bill</th>
      <th scope="col">Id Proof</th>
    </tr>
  </thead>
  <tbody>
      @foreach(var item in Model)
        {
            <tr>
                <td>@item.Name</td>
                <td>@item.HotelName</td>
                <td>@item.NoOfGuests</td>
                <td>@item.CheckInDate</td>
                <td>@item.CheckOutDate</td>
                <td>@item.RoomTypeString</td>
                <td>@item.NoOfRooms</td>
                <td>@item.RoomPrice</td>
                <td>@item.AmountPerNight</td>
                <td>@item.TotalAmount</td>
                <td>@item.IdProofType</td>
            </tr>
        }
   
  </tbody>
</table>

Views/Dashboards/UsersDashboard.cshtml
@model List<HotelsAvailable>
@inject IHttpContextAccessor context

@{
    ViewData["Title"] = "User Dashboard";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="container MainContainer">

    <div class="text-center">
        <h3>Welcome to Infinite Hotels</h3>
        <h4>Choose your Stay as per your Need</h4>
    </div>

    <div class="row MainRow justify-content-center pt-5">

        @foreach(var hotel in Model)
        {
            <div class="col-lg-4 mx-auto text-center mb-3">
                <div class="col-lg-12 mx-auto text-center MainCol shadow-lg rounded">
                    <div class="card">
                      <img class="card-img-top" src="@hotel.CoverImgUrl" alt="Card image cap">
                      <div class="card-body">
                        <h4>@hotel.HotelName</h4>
                            @if (hotel.SingleBedAc > 0 || hotel.DoubleBedAc > 0)
                            {
                                @if (!string.IsNullOrEmpty(@hotel.SingleBedAcPrice.ToString()) && Convert.ToInt32(@hotel.SingleBedAcPrice) > 0)
                                {
                                    <span>AC Rooms starting at Rs : @hotel.SingleBedAcPrice </span>
                                }
                                else
                                {
                                    <span>AC Rooms starting at Rs : @hotel.DoubleBedAcPrice </span>
                                }
                            }
                            <br />
                            @if (hotel.SingleBedNonAc > 0 || hotel.DoubleBedNonAc > 0)
                            {
                                @if (!string.IsNullOrEmpty(@hotel.SingleBedNonAcPrice.ToString()) && Convert.ToInt32(@hotel.SingleBedNonAcPrice) > 0)
                                {
                                    <span>Non-AC Rooms starting at Rs : @hotel.SingleBedNonAcPrice </span>
                                }
                                else
                                {
                                    <span>Non-AC Rooms starting at Rs : @hotel.DoubleBedNonAcPrice </span>
                                }
                            }
                            <br />
                            <br />
                            <span><a asp-controller="Dashboards" asp-action="SelectRooms" asp-route-id="@hotel.HotelId">View</a></span>
                      </div>
                    </div>

                </div>
            </div>
        }

    </div>
    @*<div class="row justify-content-center align-items-center">
        <div class="col-sm-12 mx-auto">
            <a href="@Url.Action("UserBookingsTab", "Dashboards", new { email = @context.HttpContext.Session.GetString("UserEmail")})">Bookings Tab</a>
        </div>
        
    </div>*@
</div>

Views/Dashboards/_ChooseRoomType.cshtml
@model List<HotelsAvailable>

<div id="choose_room" style="display:block">

    <div class="container" >
        <div class="row justify-content-center">
            <div class="text-center">
                <h4>Available Room Types</h4>
                <hr />
            </div>
            
            <div class="col-6" style="border-style: solid; border-radius: 10px;">

                @foreach(var room in Model)
                {
    
                    if(room.DoubleBedAc > 0)
                    {
                        <br />
                        <div class="row">
                            <div class="col-sm-6 d-flex justify-content-end">
                                <img src="@room.DoubleBedAcImgUrl" width="100" height="75" />
                            </div>
                            <div class="col-sm-6">
                                <span>Double Bed AC Room</span>
                                <br/>
                                <span>Price : @room.DoubleBedAcPrice</span>
                                <br/>
                                <button class="btn btn-success" onclick="location.href='@Url.Action("BookRoom", "Dashboards", new { roomType = "DoubleBedAc" , id = room.HotelId })'" id="DoubleBedAc">Book</button>
                            </div>
                        </div>
                        <hr />
        
                    }
                    if (room.SingleBedAc > 0)
                    {
                        <br />
                        <div class="row">
                            <div class="col-sm-6 d-flex justify-content-end">
                                <img src="@room.SingleBedAcImgUrl" width="100" height="75" />
                            </div>
                            <div class="col-sm-6">
                                <span>Single Bed AC Room</span>
                                <br/>
                                <span>Price : @room.SingleBedAcPrice</span>
                                <br />
                                <button class="btn btn-success" onclick="location.href='@Url.Action("BookRoom", "Dashboards", new { roomType = "SingleBedAc" , id = room.HotelId })'" id="SingleBedAc">Book</button>
                            </div>
                        </div>
                        <hr />
                    }
                    if (room.DoubleBedNonAc > 0)
                    {
                        <br />
                        <div class="row">
                            <div class="col-sm-6 d-flex justify-content-end">
                                <img src="@room.DoubleBedNonAcImgUrl" width="100" height="75" />
                            </div>
                            <div class="col-sm-6">
                                <span>Double Bed Non AC Room</span>
                                <br/>
                                <span>Price : @room.DoubleBedNonAcPrice</span>
                                <br />
                                <button class="btn btn-success" onclick="location.href='@Url.Action("BookRoom", "Dashboards", new { roomType = "DoubleBedNonAc" , id = room.HotelId })'" id="DoubleBedNonAc">Book</button>
                            </div>
                        </div>
                        <hr />
                    }
                    if (room.SingleBedNonAc > 0)
                    {
                        <br />
                        <div class="row">
                            <div class="col-sm-6 d-flex justify-content-end">
                                <img src="@room.SingleBedNonAcImgUrl" width="100" height="75" />
                            </div>
                            <div class="col-sm-6">
                                <span>Single Bed Non AC Room</span>
                                <br/>
                                <span>Price : @room.SingleBedNonAcPrice</span>
                                <br/>
                                <button class="btn btn-success" onclick="location.href='@Url.Action("BookRoom", "Dashboards", new { roomType = "SingleBedNonAc" , id = room.HotelId })'" id="SingleBedNonAc">Book</button>
                            </div>
                        </div>
                        <hr />
                    }

                    <div class="row justify-content-center align-items-center">
                        <div class="col-sm-6 d-flex justify-content-center pb-3">
                            <button class="btn btn-outline-secondary" onclick="location.href='@Url.Action("UsersDashboard", "Dashboards")'">Back</button>
                        </div>
                    </div>

                }
            </div>
        </div>
    </div>

</div>

Views/Dashboards/_SelectedRoomUserDetails.cshtml
@model BookingDetails